spring:
   datasource:
     url: jdbc:h2:tcp://localhost/~/pwc
     driverClassName: org.h2.Driver  
     username: sa 
     password: 
   h2:
     console:
       enabled: true
   jpa:
     show-sql: true
     properties:
       hibernate:
         dialect: org.hibernate.dialect.H2Dialect
server:
     port: 9000
     